### ISSUE TITLE
Provide path to ffmpeg on init

### ISSUE THREAD

**Issue by nehoraigold** [parshap/node-ffmetadata#27]
Idea for an improvement: right now, the module searches for the path to ffmpeg via either PATH or FFMPEG_PATH. It would be nice to be able to provide a path to ffmpeg on init rather than relying strictly on environmental variables. (Obviously if no path is provided, then environmental variables can be used to discern the path.) Thoughts?

**Comment by parshap** [comment]
Makes sense to me! I would happily accept a patch for that.

**Comment by nehoraigold** [comment]
Great! I submitted a pull request with the easiest possible implementation. :)
