### ISSUE TITLE
Writing metadata in mp4 removes its audio

### ISSUE THREAD

**Issue by Facuiguacel** [parshap/node-ffmetadata#34]
Hi, basically I'm trying to write some metadata to an mp4 video but after doing so, somehow the video no longer plays the audio track.

**Comment by digustingstan** [comment]
sameeeeeeeeee

**Comment by Funtime60** [comment]
The issue is that it only preserves the FIRST stream, which is bad.

**Comment by Funtime60** [comment]
You do know that the fix is already sitting in the PRs for like, 6 years IIRC.
